### ISSUE TITLE
Apodizing Kernels docs suggestions

### ISSUE THREAD

**Issue by keflavich** [Astroua/TurbuStat#206]
The apodizing kernels docs are great, but they taper off in detail at the end and could use some expansion.

In the first power spectrum figure, there appears to be a hole at the center of the 2D power spectrum.  What is this hole?  It doesn't look like it should be there.  Is the center of the 2D PSD nan'd or zero'd out by ``low_cut``?  If so, just mention it in the text.

In the partial power-spectrum figure, it would be helpful to show the cutout of the input image.  I'm also confused about the differences in the first power-spectrum figure, which is very smooth and apparently noiseless, and the partial power-spectrum, which is apparently very noisy.  Is the noise just minimized when you use a (2x2)-times larger image?  Also, why is the 'hole' gone in this image?

Finally, at least one of the 2D PSDs should be shown for the apodizing kernels.  It might be nice to show all four, but if they're nearly identical, just one is fine.  It should still differ significantly from the truncated-image 2D PSD, right?

**Comment by e-koch** [comment]
Good points. I've added some explanations in the tutorial to your questions in #205.

The hole is b/c the mean value of the field is 0. I've added a note in the apodizing kernels about this. It's present in other images, too, but I think this is the only place where it is noticeable in the image.

The "noise" is because the field is no longer fully sampled, and the hole gets filled in is because the partial image's mean is no longer 0.

Added one 2D PSD of the Tukey kernel as an example.

The end of the tutorial makes stronger recommendations for what users should consider when choosing the kernel type to use. I think of it as a trade-off between minimizing ringing and the range of frequencies that is biased by the kernel.
