### ISSUE TITLE
Delta-variance docs suggestions

### ISSUE THREAD

**Issue by keflavich** [Astroua/TurbuStat#207]
It would be helpful to show the test data images at the top.

Is there any reason you're using hydro-sim data rather than red noise spectra for this example?

On the `nan_interpolate` section, you might instead suggest setting the `preserve_nan` option:
http://docs.astropy.org/en/stable/api/astropy.convolution.convolve_fft.html#astropy.convolution.convolve_fft
which will ignore NaNs during the convolution, but then set all pixels that were originally NaN to be NaN again.  This is the best approach if all of the NaNs are on the edges; if you have NaNs on the edges *and* in the image, you have to do some manual work to keep the edges nan'd out and the interiors properly interpolated.

Can you describe further what the issues are with astropy v1 vs v2 convolution?   The only behavior that should have changed is with direct convolution (non-fft) in the case that NaNs are present; the v1 version was wrong for most use cases.

**Comment by e-koch** [comment]
There were deviations in the delta-variance values on large scales (>1/2 the image size) when using convolve_fft from v1 and v2. I think it had something to do with the edge handling but I'm having trouble making a conda environment with astropy <v2 right now to be sure... There was no difference on smaller scales, which is really the only important part to get the index of the delta-variance curve,

I've made astropy v2 the minimum requirement in #208 so that the large scale discrepancy won't be encountered.

**Comment by e-koch** [comment]
Addressed in #205. There's now a page describing the hydro data that is used in the tutorials and the zeroth moments of both data sets are shown there.

I've also clarified in 205 that the default setting is `nan_treatment='fill'` as the edge effects can be severe and are hard to understand without prior knowledge the convolve_fft settings. There are comparisons of how masking affects the delta-variance shape in another new page on how to handle noisy data.
