### ISSUE TITLE
Use scipy.stats.binned_statistic

### ISSUE THREAD

**Issue by e-koch** [Astroua/TurbuStat#82]
http://scipy.github.io/devdocs/generated/scipy.stats.binned_statistic.html#scipy.stats.binned_statistic

Drop this into radialProfile. Will require a bit of rewriting.

**Comment by keflavich** [comment]
I think it will only affect the standard deviation component (and may permit the creation of other variants).  For the other, we still need to compute a *weighted* mean, which can't be done by `binned_statistic` afaict.

**Comment by e-koch** [comment]
I guess you could also bin the weights with ```binned_statistic```? Maybe there's no advantage to doing so.

**Comment by keflavich** [comment]
Well, I think there is because then you can compute a weighted variance / weighted standard deviation.  It would then make [this line](https://github.com/keflavich/image_tools/blob/master/image_tools/radialprofile.py#L72) look like [this line](https://github.com/keflavich/image_tools/blob/master/image_tools/radialprofile.py#L74) but with `binned_statistic` in place of `histogram`.  I think.  Maybe.

**Comment by e-koch** [comment]
Addressed in #92
